### ISSUE TITLE
Add google auth key to user model.

### ISSUE THREAD

**Issue by polston** [polston/cs496#30]
The current plan is to use the npm passport module to help ease the processes of getting user authentication working.

**Comment by alittle99** [comment]
User model has been updated to support OAuth2 functionality.
Google Profile ID and access tokens are now stored alongside user information. Name and email are also requested.

**Comment by alittle99** [comment]
User model has been updated to support OAuth2 functionality.
Google Profile ID and access tokens are now stored alongside user information. Name and email are also requested.
